[debug] [2018-06-21T07:51:31.869Z] ----------------------------------------------------------------------
[debug] [2018-06-21T07:51:31.871Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase login
[debug] [2018-06-21T07:51:31.871Z] CLI Version:   3.18.6
[debug] [2018-06-21T07:51:31.871Z] Platform:      win32
[debug] [2018-06-21T07:51:31.871Z] Node Version:  v8.11.3
[debug] [2018-06-21T07:51:31.872Z] Time:          Thu Jun 21 2018 09:51:31 GMT+0200 (Paris, Madrid (heure d’été))
[debug] [2018-06-21T07:51:31.872Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=826779312&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2018-06-21T07:52:27.237Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 { code: '4/AACbW6sGJKDdPCiit7Nv4sQJpsdK0Ty4oYW9pp4ySf_nlmAOJ_0b8oLXxt-CIv0_Mftj4Ci7ZvQPg3r7-MsRZds',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code' } 
 Thu Jun 21 2018 09:52:27 GMT+0200 (Paris, Madrid (heure d’été))
[debug] [2018-06-21T07:52:31.091Z] Token Fetch Error: Error
    at new FirebaseError (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\lib\error.js:11:16)
    at Request._callback (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:35:11)
    at self.callback (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
[debug] [2018-06-21T07:52:52.052Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 { code: '4/AAAkThRwD20d7vBSKpQfgL-H_CYNxcvvw5dKrY9pbKItvovV6vFZopSIZucA-QhnVNmGUN0qH4G30mshG0UcsgY',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code' } 
 Thu Jun 21 2018 09:52:52 GMT+0200 (Paris, Madrid (heure d’été))
[debug] [2018-06-21T07:52:56.046Z] Token Fetch Error: Error
    at new FirebaseError (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\lib\error.js:11:16)
    at Request._callback (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:35:11)
    at self.callback (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
[debug] [2018-06-21T07:53:11.495Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 { code: '4/AAAkThRwD20d7vBSKpQfgL-H_CYNxcvvw5dKrY9pbKItvovV6vFZopSIZucA-QhnVNmGUN0qH4G30mshG0UcsgY',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code' } 
 Thu Jun 21 2018 09:53:11 GMT+0200 (Paris, Madrid (heure d’été))
[debug] [2018-06-21T07:53:15.984Z] Token Fetch Error: Error
    at new FirebaseError (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\lib\error.js:11:16)
    at Request._callback (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:35:11)
    at self.callback (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
[debug] [2018-06-21T07:56:12.450Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 { code: '4/AAAkThRwD20d7vBSKpQfgL-H_CYNxcvvw5dKrY9pbKItvovV6vFZopSIZucA-QhnVNmGUN0qH4G30mshG0UcsgY',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code' } 
 Thu Jun 21 2018 09:56:12 GMT+0200 (Paris, Madrid (heure d’été))
[debug] [2018-06-21T07:56:15.837Z] Token Fetch Error: Error
    at new FirebaseError (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\lib\error.js:11:16)
    at Request._callback (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:35:11)
    at self.callback (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
[debug] [2018-06-21T07:57:53.407Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 { code: '4/AAAkThRwD20d7vBSKpQfgL-H_CYNxcvvw5dKrY9pbKItvovV6vFZopSIZucA-QhnVNmGUN0qH4G30mshG0UcsgY',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code' } 
 Thu Jun 21 2018 09:57:53 GMT+0200 (Paris, Madrid (heure d’été))
[debug] [2018-06-21T07:57:56.456Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 { code: '4/AAAkThRwD20d7vBSKpQfgL-H_CYNxcvvw5dKrY9pbKItvovV6vFZopSIZucA-QhnVNmGUN0qH4G30mshG0UcsgY',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code' } 
 Thu Jun 21 2018 09:57:56 GMT+0200 (Paris, Madrid (heure d’été))
[debug] [2018-06-21T07:57:57.826Z] Token Fetch Error: Error
    at new FirebaseError (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\lib\error.js:11:16)
    at Request._callback (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:35:11)
    at self.callback (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
[debug] [2018-06-21T07:57:57.827Z] Token Fetch Error: Error
    at new FirebaseError (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\lib\error.js:11:16)
    at Request._callback (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:35:11)
    at self.callback (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
[debug] [2018-06-21T08:05:21.986Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 { code: '4/AAAkThRwD20d7vBSKpQfgL-H_CYNxcvvw5dKrY9pbKItvovV6vFZopSIZucA-QhnVNmGUN0qH4G30mshG0UcsgY',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code' } 
 Thu Jun 21 2018 10:05:21 GMT+0200 (Paris, Madrid (heure d’été))
[debug] [2018-06-21T08:05:25.511Z] Token Fetch Error: Error
    at new FirebaseError (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\lib\error.js:11:16)
    at Request._callback (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:35:11)
    at self.callback (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\vlkimm\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
